blackan.http.server.port=8080

# MySQL Database Configuration
jakarta.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/blackan?useSSL=false&allowPublicKeyRetrieval=true
jakarta.persistence.jdbc.user=blackan
jakarta.persistence.jdbc.password=blackan

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true